[custom.all.common]
type = "local"
path = "../common"
ipkg = "common.ipkg"

[custom.all.safe_select]
type = "local"
path = "."
ipkg = "safe_select.ipkg"
test = "test/test.ipkg"

[custom.all.safe_select-test]
type = "local"
path = "test"
ipkg = "test.ipkg"
